### ISSUE TITLE
Stilll not working

### ISSUE THREAD

**Issue by saYRam** [lastlink/EFPowerToolsExample#1]
vs2015 pro update 3. i uninstalled original version. installed your version. still getting error.

**Comment by PerryCodes** [comment]
I can verify the same result. Still not working in VS 2015. I'm using update 3 as well.

**Comment by lastlink** [comment]
Where is the error occurring? Were you able to install the extension. vs 2015 update 3 works for me. This project should be run separate from your own project then imported into your project to pull the generated models over. Sometimes it fails to reverse engineer and the fix is to change the .net version of this project. e.g. 4.52 to 4.51 etc.
